version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: portfolio-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

  springboot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: portfolio-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    restart: always
    ports:
      - "81:81"
    depends_on:
      - springboot
    volumes:
      - ../nginx/sites-available:/etc/nginx/sites-available
      - ../nginx/sites-enabled:/etc/nginx/sites-enabled

volumes:
  mysql-data:
