version: "3.8"

services:

  portfolio-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: portfolio-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - portfolio-network
    depends_on:
      - portfolio-db

  portfolio-db:
    image: mysql:8
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio-network

  portfolio-nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/sites-available:/etc/nginx/sites-available
    depends_on:
      - portfolio-app
    networks:
      - portfolio-network

networks:
  portfolio-network:

volumes:
  db-data:
