version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: portfolio-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    volumes:
      - mysql-data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio-net

  springboot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: portfolio-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - portfolio-net

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    restart: always
    depends_on:
      - springboot
    ports:
      - "81:81"
    volumes:
      - ../nginx/sites-enabled:/etc/nginx/conf.d
    networks:
      - portfolio-net

volumes:
  mysql-data:

networks:
  portfolio-net:
