pipeline {

    agent { label 'rohit-agent-1' }

    triggers {
        githubPush()
    }

    stages {

        stage('Cleanup') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'master',
                url: 'https://github.com/rohitrawat025/devops-aws-jenkins-docker-cicd-platform.git'
            }
        }

        stage('Build Application') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker compose -f docker/docker-compose.yml build'
            }
        }

        stage('Deploy Containers') {
            steps {
                sh 'docker compose -f docker/docker-compose.yml up -d'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'docker ps'
                sh 'curl http://localhost:81 || true'
            }
        }

    }

}
