pipeline {

    agent { label 'rohit-agent-1' }

    triggers {
        githubPush()
    }

    environment {
        COMPOSE_FILE = "docker/docker-compose.yml"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Verify Repository') {
            steps {
                sh '''
                echo "Repository structure:"
                ls -la
                '''
            }
        }

        stage('Prepare Nginx Config') {
            steps {
                sh '''
                mkdir -p nginx/sites-enabled
                cp nginx/sites-available/nw-nginx.conf nginx/sites-enabled/
                '''
            }
        }

        stage('Full Docker Cleanup') {
            steps {
                sh '''
                echo "Stopping containers..."

                docker compose -f $COMPOSE_FILE down -v || true

                echo "Removing unused images..."
                docker system prune -af || true
                '''
            }
        }

        stage('Build Docker Images') {
            steps {
                sh '''
                docker compose -f $COMPOSE_FILE build
                '''
            }
        }

        stage('Deploy Containers') {
            steps {
                sh '''
                docker compose -f $COMPOSE_FILE up -d
                '''
            }
        }

        stage('Wait For Application') {
            steps {
                sh '''
                echo "Waiting for application..."

                for i in {1..20}
                do
                    if curl -s http://localhost:81 > /dev/null; then
                        echo "Application is ready"
                        exit 0
                    fi

                    echo "Waiting..."
                    sleep 5
                done

                echo "Application failed to start"
                exit 1
                '''
            }
        }

    }

    post {

        success {
            sh '''
            echo "Application URL:"
            curl -s ifconfig.me
            '''
        }

        failure {
            sh '''
            echo "Deployment failed"

            docker ps -a
            docker logs portfolio-app || true
            '''
        }

    }

}
